function handles = plot_phase_field_3d(filename, varargin)
%PLOT_PHASE_FIELD_3D Plot the local MPS fraction from phase_field output.
%
%   plot_phase_field_3d('phase_field_final.CASE.dat')
%
%   plot_phase_field_3d(..., 'MaxMarkerArea', 180, ...
%                            'MarkerAlpha', 0.60, ...
%                            'MinMPSFraction', 0.00)
%
% The input must be the 10-column phase_field table generated by
% phase_separation_analyzer.cpp. Marker area and marker color are both
% proportional to the local MPS repeat fraction in column 10. Empty voxels
% and occupied voxels with no MPS markers are not drawn.

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, 'filename', @(x) ischar(x) || isstring(x));
addParameter(parser, 'MaxMarkerArea', 180, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(parser, 'MarkerAlpha', 0.65, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0 && x <= 1);
addParameter(parser, 'MinMPSFraction', 0, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 0 && x < 1);
parse(parser, filename, varargin{:});
options = parser.Results;

field = load(char(filename), '-ascii');
if ~isnumeric(field) || isempty(field) || size(field, 2) ~= 10
    error('plot_phase_field_3d:InvalidInput', ...
        'Expected a nonempty, numeric phase_field table with 10 columns.');
end
if any(~isfinite(field(:)))
    error('plot_phase_field_3d:NonfiniteInput', ...
        'The phase_field table contains NaN or Inf values.');
end

occupied = field(:, 9) > 0;
fraction = field(:, 10);
fractionTolerance = 1.0e-10;
if any(fraction(occupied) < -fractionTolerance | ...
       fraction(occupied) > 1 + fractionTolerance)
    error('plot_phase_field_3d:InvalidFraction', ...
        'Occupied-voxel MPS fractions must lie between zero and one.');
end
fraction = min(1, max(0, fraction));

selected = occupied & fraction > options.MinMPSFraction;
if ~any(selected)
    error('plot_phase_field_3d:NoMPSVoxels', ...
        'No occupied voxels exceed the requested minimum MPS fraction.');
end

coordinates = field(selected, 4:6);
mpsFraction = fraction(selected);
markerArea = options.MaxMarkerArea .* mpsFraction;

figureHandle = figure('Color', 'w');
axesHandle = axes('Parent', figureHandle);
scatterHandle = scatter3(axesHandle, ...
    coordinates(:, 1), coordinates(:, 2), coordinates(:, 3), ...
    markerArea, mpsFraction, 'filled', ...
    'MarkerFaceAlpha', options.MarkerAlpha, ...
    'MarkerEdgeAlpha', min(1, options.MarkerAlpha + 0.15));

axis(axesHandle, 'equal');
axis(axesHandle, 'tight');
grid(axesHandle, 'on');
box(axesHandle, 'on');
view(axesHandle, 3);
rotate3d(figureHandle, 'on');
xlabel(axesHandle, 'x (Angstrom)');
ylabel(axesHandle, 'y (Angstrom)');
zlabel(axesHandle, 'z (Angstrom)');
title(axesHandle, sprintf('3D MPS composition map: %s', char(filename)), ...
    'Interpreter', 'none');

colormap(axesHandle, parula(256));
caxis(axesHandle, [0 1]);
colorbarHandle = colorbar(axesHandle);
colorbarHandle.Label.String = 'Local MPS repeat fraction';

if nargout > 0
    handles.figure = figureHandle;
    handles.axes = axesHandle;
    handles.scatter = scatterHandle;
    handles.colorbar = colorbarHandle;
end
end
