#define SILICONE_FORMULATION_NAME "V22"
#define SILICONE_DEFAULT_N1 128
#define SILICONE_DEFAULT_M1 900
#define SILICONE_DEFAULT_FUNCTIONALITY 8
#define SILICONE_FOLDED_NETWORK 0
#define SILICONE_CROSSLINK_PROBABILITY 0.1

#include "../V35/v35_generator.cpp"
